### ISSUE TITLE
MKS robin Nano V3.0 Custom CNC

### ISSUE THREAD

**Issue by xNeurosynapticx** [makerbase-mks/Marlin-V2.X-MKS-H43#9]
Hello, my MKS setup is a MKS robin Nano V3.0 wifi+MKS TS35 V2.0+ MKS H43 V1.0+4un MKS Servo 57b V2.0 on a custom CNC Machine. I have a few questions:

I try to compile both TS35 and H43 firmware but I got this error:
Marlin\src\HAL\STM32\../../inc/SanityCheck.h:2342:4: error: #error "Please select only one LCD controller option."

Can it be possible to have both TS32 and H43 running at the same time?

//////////////////////////////////////////////////////////////////////////////////////////////

I compiled every firmware (Mks-Robin-Nano-Marlin2.0-Firmware) (Marlin-V2.X-MKS-H43) and the only one that is seems to work almost perfect its the MKS-Robin-Nano-V3.X (MKS-Robin-Nano-V3.X/firmware/Marlin-bugfix2.0.x-MKS-2.1.2/Firmware bin for support SD card/Firmware bin for Ender3(4988)/
). except for a little issue.
when I'm printing, every time that I change the screen to another screen its stall  +-0.5 seconds to load the new screen. ( example if I'm printing and I press options)

is it possible to fix this?

/////////////////////////////////////////////////////////////////////////////////////////////

I installed the firmware (H43_Firmware_1.31 and 1.30) but both gets stuck after the intro animation. I created a (basic touch module) in DGUS7618 software to skip to the main screen. still I'm trying to get it work with the robin nano v3.0. 

can you upload the firmware of a MKS robin Nano V3.0 + WIFI to (makerbase-mks/MKS-H43)?

/////////////////////////////////////////////////////////////////////////////////////////////

**Comment by xNeurosynapticx** [comment]
Robin_nano_v3.zip

https://drive.google.com/file/d/1-xtct92XxQM_H869CIb3FjITY8hm4ljc/view?usp=sharing

FULLY functional firmware for Robin nano v3.0 + H43 fw 1.30 + TS32 + WIFI +Serial comunication

**Comment by ghost** [comment]
> Hello, my MKS setup is a MKS robin Nano V3.0 wifi+MKS TS35 V2.0+ MKS H43 V1.0+4un MKS Servo 57b V2.0 on a custom CNC Machine. I have a question:
> 
> I try to compile both TS35 and H43 firmware but I got this error:
> Marlin\src\HAL\STM32../../inc/SanityCheck.h:2342:4: error: #error "Please select only one LCD controller option."
> 
> Can it be possible to have both TS32 and H43 running at the same time?

MKS_ H43 can't realize multi screen function, its use is different from ts35

**Comment by edensan2** [comment]
> Hallo, mijn MKS-installatie is een MKS Robin Nano V3.0 wifi+MKS TS35 V2.0+ MKS H43 V1.0+4un MKS Servo 57b V2.0 op een aangepaste CNC-machine. Ik heb een vraag:
> 
> Ik probeer zowel TS35- als H43-firmware te compileren, maar ik krijg deze foutmelding: Marlin\src\HAL\STM32../../inc/SanityCheck.h:2342:4: error: #error "Selecteer slechts één LCD -controlleroptie."
> 
> Is het mogelijk om zowel TS32 als H43 te laten draaien?

How do you control your cnc? Is it just plain marlin? Or did you change it for specific router functions? Can you share your firmware? 
Im building a cnc but i cant get the software right.
I dont understand how to run a gcode on a 3dprinter like menu example how do yo zerro your axis on top of the workpiece ? Tgat sort of things.

I have a nano v3.1 with tft35 and external drivers including adapter module extreem high power swiching (bcs nano send 3V in stead of 5V) and dm556 drivers and nema 23 motors

So anny help is more then welcome
Greetz from Holland
